name: "devsecops-action"
description: "Foo bar."
inputs:
  d:
    description: "Source directory to scan. Defaults to workspace"
    required: false
    default: "/github/workspace"
  o:
    description: "Output directory for the generated reports. Defaults to reports"
    required: false
    default: "/github/workspace/reports"
runs:
  using: "docker"
  image: "docker://opensecurity/nodejsscan:cli"
  args:
    - "-d"
    - ${{ inputs.src }}
    - "-o"
    - ${{ inputs.output }}
branding:
  icon: "check"
  color: "blue"
