name: "devsecops-action"
description: "Foo bar."
runs:
  using: "docker"
  image: "docker://opensecurity/nodejsscan:cli"
  args:
    - "-d"
    - ${{ inputs.src }}
    - "-o"
    - ${{ inputs.output }}
branding:
  icon: "shied"
  color: "green"
